-- Java LSP support via nvim-jdtls (optional)
-- Uncomment and configure when Java development is needed.
--
-- Prerequisites:
--   1. Install jdtls via Mason: :MasonInstall jdtls
--   2. Adjust the paths below to match your system
--
-- local status, jdtls = pcall(require, "jdtls")
-- if not status then
--   return
-- end
--
-- local root_dir = require("jdtls.setup").find_root({ "mvnw", "gradlew", "pom.xml", "build.gradle" })
-- if root_dir == "" then
--   return
-- end
--
-- local data_dir = vim.fn.getcwd() .. "/.jdtls"
-- local home = os.getenv("HOME")
-- local mason_path = vim.fn.stdpath("data") .. "/mason"
--
-- local config = {
--   cmd = {
--     "java",
--     "-Declipse.application=org.eclipse.jdt.ls.core.id1",
--     "-Dosgi.bundles.defaultStartLevel=4",
--     "-Declipse.product=org.eclipse.jdt.ls.core.product",
--     "-Dlog.protocol=true",
--     "-Dlog.level=ALL",
--     "-Xmx1g",
--     "--add-modules=ALL-SYSTEM",
--     "--add-opens", "java.base/java.util=ALL-UNNAMED",
--     "--add-opens", "java.base/java.lang=ALL-UNNAMED",
--     "-jar", vim.fn.glob(mason_path .. "/packages/jdtls/plugins/org.eclipse.equinox.launcher_*.jar"),
--     "-configuration", mason_path .. "/packages/jdtls/config_linux",
--     "-data", data_dir,
--   },
--   capabilities = require("blink.cmp").get_lsp_capabilities(),
--   root_dir = root_dir,
--   settings = {
--     java = {
--       eclipse = { downloadSources = true },
--       configuration = { updateBuildConfiguration = "interactive" },
--       maven = { downloadSources = true },
--       implementationsCodeLens = { enabled = true },
--       referencesCodeLens = { enabled = true },
--       references = { includeDecompiledSources = true },
--       inlayHints = { parameterNames = { enabled = "all" } },
--       format = { enabled = false },
--     },
--     signatureHelp = { enabled = true },
--     contentProvider = { preferred = "fernflower" },
--   },
--   on_attach = function(client, bufnr)
--     pcall(vim.lsp.codelens.refresh)
--   end,
-- }
--
-- jdtls.start_or_attach(config)
